In [12]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [13]:
df = pd.read_csv("Customer_Churn_Data_V2.csv")
print(df['Churn'].value_counts())
print(df['Churn'].value_counts(normalize=True) * 100)

Churn
0    5163
1    1869
Name: count, dtype: int64
Churn
0    73.421502
1    26.578498
Name: proportion, dtype: float64

In [14]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,PaperlessBilling,MonthlyCharges,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Contract_Month-to-month,Contract_One year,Contract_Two year,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes
0,7590-VHVEG,0,0,1,0,1,0,No phone service,1,29.85,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,5575-GNVDE,1,0,0,0,34,1,No,0,56.95,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
2,3668-QPYBK,1,0,0,0,2,1,No,1,53.85,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
3,7795-CFOCW,1,0,0,0,45,0,No phone service,0,42.30,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,9237-HQITU,0,0,0,0,2,1,No,1,70.70,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,6840-RESVB,1,0,1,1,24,1,Yes,1,84.80,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
7028,2234-XADUH,0,0,1,1,72,1,Yes,1,103.20,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
7029,4801-JZAZL,0,0,1,1,11,0,No phone service,1,29.60,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
7030,8361-LTMKD,1,1,1,0,4,1,Yes,1,74.40,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
7031,3186-AJIEK,1,0,0,0,66,1,No,1,105.65,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

In [15]:
df.drop(columns=['customerID','MonthlyCharges'], inplace=True)

In [16]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,PaperlessBilling,TotalCharges,Churn,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Contract_Month-to-month,Contract_One year,Contract_Two year,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes
0,0,0,1,0,1,0,No phone service,1,29.85,0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,1,0,0,0,34,1,No,0,1889.50,0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
2,1,0,0,0,2,1,No,1,108.15,1,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
3,1,0,0,0,45,0,No phone service,0,1840.75,0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,0,0,0,0,2,1,No,1,151.65,1,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,1,0,1,1,24,1,Yes,1,1990.50,0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
7028,0,0,1,1,72,1,Yes,1,7362.90,0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
7029,0,0,1,1,11,0,No phone service,1,346.45,0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
7030,1,1,1,0,4,1,Yes,1,306.60,1,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
7031,1,0,0,0,66,1,No,1,6844.50,0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

In [17]:
df.to_csv("Customer_Churn_Data_V3.csv", index=False)